"""initial schema

Revision ID: 80039962503f
Revises: 
Create Date: 2026-07-21 16:18:48.335298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80039962503f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('job_posting_url', sa.String(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('career_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('current_year', sa.String(length=50), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('current_industry', sa.String(length=255), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=False),
    sa.Column('technical_skills', sa.JSON(), nullable=False),
    sa.Column('dsa_level', sa.String(length=30), nullable=False),
    sa.Column('system_design_level', sa.String(length=30), nullable=False),
    sa.Column('behavioral_confidence', sa.String(length=30), nullable=False),
    sa.Column('preferred_language', sa.String(length=100), nullable=True),
    sa.Column('improvement_areas', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('target_companies', sa.JSON(), nullable=False),
    sa.Column('target_industries', sa.JSON(), nullable=False),
    sa.Column('target_locations', sa.JSON(), nullable=False),
    sa.Column('position_types', sa.JSON(), nullable=False),
    sa.Column('workplace_preferences', sa.JSON(), nullable=False),
    sa.Column('application_timeline', sa.String(length=255), nullable=True),
    sa.Column('primary_goal', sa.Text(), nullable=True),
    sa.Column('salary_expectations', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_profiles_user_id'), 'career_profiles', ['user_id'], unique=True)
    op.create_table('coach_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_interactions_user_id'), 'coach_interactions', ['user_id'], unique=False)
    op.create_table('coach_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_policies_user_id'), 'coach_policies', ['user_id'], unique=True)
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_applications', sa.Integer(), nullable=False),
    sa.Column('pending_applications', sa.Integer(), nullable=False),
    sa.Column('interviewing', sa.Integer(), nullable=False),
    sa.Column('offers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('interview_rate', sa.Float(), nullable=False),
    sa.Column('offer_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_user_id'), 'dashboard', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_resume_id'), 'analysis', ['resume_id'], unique=False)
    op.create_index(op.f('ix_analysis_user_id'), 'analysis', ['user_id'], unique=False)
    op.create_table('coach_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_sessions_application_id'), 'coach_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_coach_sessions_resume_id'), 'coach_sessions', ['resume_id'], unique=False)
    op.create_index(op.f('ix_coach_sessions_user_id'), 'coach_sessions', ['user_id'], unique=False)
    op.create_table('analysis_bullets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('bullet_index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('rewrite_ats', sa.Text(), nullable=True),
    sa.Column('rewrite_strong', sa.Text(), nullable=True),
    sa.Column('missing_keywords_csv', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_bullets_run_id'), 'analysis_bullets', ['run_id'], unique=False)
    op.create_table('coach_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_questions_session_id'), 'coach_questions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_questions_session_id'), table_name='coach_questions')
    op.drop_table('coach_questions')
    op.drop_index(op.f('ix_analysis_bullets_run_id'), table_name='analysis_bullets')
    op.drop_table('analysis_bullets')
    op.drop_index(op.f('ix_coach_sessions_user_id'), table_name='coach_sessions')
    op.drop_index(op.f('ix_coach_sessions_resume_id'), table_name='coach_sessions')
    op.drop_index(op.f('ix_coach_sessions_application_id'), table_name='coach_sessions')
    op.drop_table('coach_sessions')
    op.drop_index(op.f('ix_analysis_user_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_resume_id'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_dashboard_user_id'), table_name='dashboard')
    op.drop_table('dashboard')
    op.drop_index(op.f('ix_coach_policies_user_id'), table_name='coach_policies')
    op.drop_table('coach_policies')
    op.drop_index(op.f('ix_coach_interactions_user_id'), table_name='coach_interactions')
    op.drop_table('coach_interactions')
    op.drop_index(op.f('ix_career_profiles_user_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
